name: "GLPI CI"

on:
  # Runs test suite when a new commit is pushed on "main" and "*/bugfixes" branches
  # and when a new tag is created
  push:
    branches:
      - main
      - '*/bugfixes'
      - 'feature/*'
      - 'fix/*'
      - 'security/*'
    tags:
       - '*'
  # Runs test suite when a PR is opened or synchronyzed
  pull_request:
  # Runs test suite every night
  schedule:
    - cron:  '0 0 * * *'
  # Enable manual run
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  generate-tests-matrix:
    # Do not run scheduled tests on tier repositories
    if: github.repository == 'glpi-project/glpi' || github.event_name != 'schedule'
    permissions:
      contents: "read"
    name: "Generate tests matrix"
    runs-on: "ubuntu-latest"
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - name: "Generate matrix"
        id: "generate-matrix"
        run: |
          if [[ "${{ github.event_name }}" = "workflow_dispatch" || ( "${{ github.ref_type }}" = "branch" && "${{ github.ref_name }}" =~ ^(main|.*/bugfixes|security/.*)$ ) || "${{ github.ref_type }}" = "tag" ]]; then
            MATRIX='
              {
                "include": [
                  {"php-version": "8.5", "db-image": "mariadb:11.8"},
                  {"php-version": "8.2", "db-image": "mariadb:10.6"},
                  {"php-version": "8.5", "db-image": "mysql:8.4"},
                  {"php-version": "8.5", "db-image": "mysql:8.0"}
                ]
              }
            '
          else
            MATRIX='
              {
                "include": [
                  {"php-version": "8.5", "db-image": "mariadb:11.8"},
                  {"php-version": "8.2", "db-image": "mysql:8.4"}
                ]
              }
            '
          fi
          echo "matrix=$(echo $MATRIX | jq -c .)" >> $GITHUB_OUTPUT
  e2e:
    # Do not run scheduled tests on tier repositories
    if: github.repository == 'glpi-project/glpi' || github.event_name != 'schedule'
    permissions:
      contents: "read"
    name: "E2E and web tests using latest PHP and MariaDB versions"
    runs-on: "ubuntu-latest"
    timeout-minutes: 90
    env:
      COMPOSE_FILE: ".github/actions/docker-compose-app.yml:.github/actions/docker-compose-services.yml"
      APPLICATION_ROOT: "${{ github.workspace }}"
      DB_IMAGE: "githubactions-mariadb:10.11"
      PHP_IMAGE: "githubactions-php-apache:8.3"
      UPDATE_FILES_ACL: true
    steps:
      - name: "Set env"
        run: |
          echo "APP_CONTAINER_HOME=${{ runner.temp }}/app_home" >> $GITHUB_ENV
      - name: "Checkout"
        uses: "actions/checkout@v6"
      - name: "Restore dependencies cache"
        uses: actions/cache@v5
        with:
          path: |
            ${{ env.APP_CONTAINER_HOME }}/.cache/composer/
            ${{ env.APP_CONTAINER_HOME }}/.npm/_cacache/
          key: "app_home_deps-8.3-${{ hashFiles('composer.lock', 'package-lock.json') }}"
          restore-keys: |
            app_home_deps-8.3-
            app_home_deps-
      - name: "Initialize containers"
        run: |
          .github/actions/init_containers-start.sh
      - name: "Show versions"
        run: |
          .github/actions/init_show-versions.sh
      - name: "Build dependencies / translations"
        run: |
          docker compose exec -T app .github/actions/init_build.sh
      - name: "Install DB tests"
        if: "${{ success() || failure() }}"
        run: |
          docker compose exec -T app .github/actions/test_install.sh
      - name: "WEB tests"
        if: "${{ success() || failure() }}"
        run: |
          docker compose exec -T app .github/actions/test_tests-web.sh
